### ISSUE TITLE
segmentation fault when loading surrogate_model.model 

### ISSUE THREAD

**Issue by yaoyang33** [automl/nas-bench-x11#1]
I'm running a segmentation fault error when loading surrogate_model.model from nb311-v0.5/ensemble_member_0

Anyone has the same problem?

**Comment by crwhite14** [comment]
Hi, try these steps:
Check if you have [nasbench](https://github.com/google-research/nasbench) installed. If not, install `tensorflow==1.15.4` using pip, and then install nasbench following their installation instructions. Note: if you have tensorflow 2, or no tensorflow at all, then the nasbench installation will fail because it was created before tensorflow 2.

Once tensorflow 1.15.4 and nasbench are installed, try to load surrogate_model.model again. We will soon update the installation instructions.

**Comment by yaoyang33** [comment]
It works now when I downgrade tf to the version you specified. Thanks!
